package org.vaadin.mytablegeneratordemo.entities;

// Generated 12.07.2013 15:41:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "mydemo", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "state_id" }))
public class City implements java.io.Serializable {

	private static final long serialVersionUID = -5071829242980695169L;
	
	private Integer id;
	private String name;
	private int stateId;

	public City() {
	}

	public City(int stateId) {
		this.stateId = stateId;
	}

	public City(String name, int stateId) {
		this.name = name;
		this.stateId = stateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state_id", nullable = false)
	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

}
